---
name: "Kitsu"
guid: "88d809e2-056b-47f4-9911-073949b9963f"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-kitsu.png"
version: 5
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Kitsu metadata provider"
description: >
  Kitsu metadata provider

category: "Metadata"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Kitsu.dll"
changelog: |-
  - 10.9 (#29) @crobibero

  ### Code or Repo Maintenance ###
  - Update link to Jellyfin website (#26) @methbkts
